using System;
using System.Collections.Generic;
using System.Text;
using UnityEngine;

/// <summary>
/// ScriptableObject that defines a craftable recipe: an ordered tree of <see cref="RecipeStepNode"/> steps,
/// the result item ID and quantity, and a human-readable description generated by <see cref="GetDisplayText"/>.
/// </summary>
[CreateAssetMenu(fileName = "New Recipe", menuName = "Recipes/Recipe")]
public class Recipe : ScriptableObject
{
    [SerializeField]
    int recipeId;

    [HideInInspector]
    public string title;
    public int totalTimesCrafted = 0;

    [TextArea(3, 12)]
    public string text;

    [Header("Execution")]
    public List<RecipeStepNode> steps = new List<RecipeStepNode>();
    public int resultItemID;
    public int resultQuantity = 1;

    public int RecipeId => recipeId;

    public string GetDisplayText()
    {
        if (!string.IsNullOrWhiteSpace(text))
        {
            return text;
        }

        if (steps == null || steps.Count == 0)
        {
            return string.Empty;
        }

        StringBuilder sb = new StringBuilder();
        AppendStepsText(steps, sb, 1);
        return sb.ToString();
    }

    private void AppendStepsText(List<RecipeStepNode> nodeList, StringBuilder sb, int startIndex)
    {
        int stepNumber = startIndex;
        for (int i = 0; i < nodeList.Count; i++)
        {
            RecipeStepNode node = nodeList[i];
            if (node == null) continue;

            if (node.nodeType == RecipeNodeType.ConsumeItem || node.nodeType == RecipeNodeType.Stir)
            {
                sb.Append(stepNumber);
                sb.Append(". ");
                sb.Append(node.GetDescription());
                if (i < nodeList.Count - 1)
                {
                    sb.AppendLine();
                }
                stepNumber++;
            }
            else if (node.nodeType == RecipeNodeType.IfElse && node.ifElseBlock != null)
            {
                sb.Append("IF ");
                if (node.ifElseBlock.condition != null)
                {
                    sb.Append(node.ifElseBlock.condition.GetDescription());
                }
                else
                {
                    sb.Append("condition");
                }
                sb.AppendLine(":");
                AppendStepsText(node.ifElseBlock.thenSteps, sb, stepNumber);
                sb.AppendLine("ELSE:");
                AppendStepsText(node.ifElseBlock.elseSteps, sb, stepNumber);
                sb.AppendLine("END IF");
            }
            else if (node.nodeType == RecipeNodeType.For && node.forBlock != null)
            {
                sb.Append("FOR ");
                sb.Append(node.forBlock.iterations);
                sb.AppendLine(" times:");
                AppendStepsText(node.forBlock.bodySteps, sb, stepNumber);
                sb.AppendLine("END FOR");
            }
        }
    }
}
